- hosts: foundry
  tasks:

    # Packages
    - name: Insert current node apt list
      shell: "curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -"

    - name: Install apt packages
      apt:
        name:
          - nodejs
          - libssl-dev
          - nginx
          - unzip
        state: present

    - name: Update package list and upgrade apt secure packages
      apt:
        update_cache: "yes"
        upgrade: "yes"    

    # Firewall configuration
    - name: Allow ssh and http(s) ports
      ufw:
          rule: allow
          port: "{{ item }}"
      with_items:
            - "22"
            - "443"
      
    - name: Disallow everything else
      ufw:
        state: enabled
        policy: deny
 
    # Foundry vtt installation and setup
    - name: Create foundry folders
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "/opt/foundry"
        - "/opt/foundry-data"
  
    - name: Extract and upload zip
      unarchive: 
        src: "foundry_zips/foundryvtt.zip"
        dest: "/opt/foundry/"

    - name: Start foundry service
      shell: "node /opt/foundry/resources/app/main.js --dataPath=/opt/foundrydata &"
      tags: foundry-service-start

    # nginx and ssl
    - name: Create Cert folder
      file:
        path: "/etc/certs"
        state: directory

    - name: Copy cert and key to server
      copy:
        src: "certs/{{ item }}.pem"
        dest: "/etc/certs"
      with_items:
        - "key"
        - "cert"

    - name: Generate nginx config
      template:
        src: templates/nginx-site.conf.j2
        dest: /etc/nginx/sites-available/{{ hostname }}
    
    - name: Activate site
      file:
        src: /etc/nginx/sites-available/{{ hostname }}
        dest: /etc/nginx/sites-enabled/{{ hostname }}
        state: link

    - name: Deactivate default Site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted

    

